### PR TITLE
Use token

### PR DESCRIPTION
**Pull request by xiphl**
forces uses to send access tokens when they send requests to ingest-api

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by xiphl** [comment]
seems like there is a network issue, some tests are failing intermittently due to unsuccessful downloads

**Comment by xiphl** [comment]
take note that env in docker/datahub-gms and  docker/datahub-frontend-react needs to set METADATA_SERVICE_AUTH_ENABLED = true.
I cannot set the flag permanently true in github else smoke test will fail. (all the tests needs a token to ingest stuff)

**Review by neojunjie — CHANGES_REQUESTED** [review]
do you want to comment your console.log messages?
if not it will be shipped to production build

**Comment by xiphl** [comment]
K I'll comment out first then commit again

**Review by neojunjie — APPROVED** [review]

**Pull request merged**
