### PR TITLE
Migrate pipeline

### PR DESCRIPTION
**Pull request by xiphl**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by xiphl** [comment]
Trino ingestion tests has not been passing in the upstream repo for a while.
pulling the delta in trino code also does not solve the problem.

**Comment by xiphl** [comment]
lesson: always check the upstream tests result + look at the code differences + setup.py version differences, between this repo and the upstream, before deciding to jump all in to run the ingestion test locally.

**Comment by xiphl** [comment]
oops, missed out hana_ingest

**Comment by xiphl** [comment]
to squash all the commits as a single commit later

**Comment by neojunjie** [comment]
handled by another PR

**Pull request closed without merging**
